### ISSUE TITLE
Isn't there an english version for the same ?

### ISSUE THREAD

**Issue by kiranruth** [ChillarAnand/tpint#1]
Isn't there an english version for the same ?

**Comment by ChillarAnand** [comment]
Currently, it's not there. We should make it configurable so that users can choose any language as well as and can put their own custom proverbs list.

**Comment by kiranruth** [comment]
I've created a pull request on the same @ChillarAnand 
https://github.com/ChillarAnand/tpint/pull/2

**Comment by ChillarAnand** [comment]
Thanks, @kiranruth.

Closing this issue.
